### ISSUE TITLE
[EPIC] Améliorer la build GitHub action

### ISSUE THREAD

**Issue by thbar** [etalab/transport-tools#5]
Pour l'instant c'est prématuré car on ne s'en sert pas fortement, toutefois:
- [ ] Il faudra implémenter un système de cache (#4)
- [x] ~~Utiliser le tag `latest` pour l'image générée (convention Docker) plutôt que `master`~~
- [x] ~~Peut-être ne construire que lorsqu'on crée une release (à voir)~~
- [x] Tester l'image avant de la pusher (#3)
- [x] Geler les commits des repositories de code utilisés (Rust) quand possible #15

**Comment by thbar** [comment]
Je clôture pour l'instant.
